---
##################################################
# RESOURCES
##################################################
resources:
- name: pipeline
  type: git
  source:
    uri: {{pipeline-git-uri}}
    branch: {{pipeline-git-branch}}
    #private_key: {{git-private-key}}

##################
#### PCF
##################
- name: cf-test
  type: cf
  source:
    api: {{cf-api-url}}
    skip_cert_check: true
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}

#################
#### Simple DOTNET
#################
- name: simple-dotnet
  type: git
  source:
    uri: {{simple-dotnet-git-uri}}
    branch: {{simple-dotnet-git-branch}}

- name: simple-dotnet-version
  type: semver
  source:
    driver: git
    uri: {{simple-git-version-uri}}
    branch: {{simple-git-version-branch}}
    file: number-simple-dotnet
    initial_version: 1.0.0
    private_key: {{git-private-key}}

##################################################
# JOBS
##################################################
jobs:

# Build, Store, Version
- name: build-simple-dotnet
  plan:
  - aggregate:
    - get: pipeline
    - get: project
      resource: simple-dotnet
      trigger: true
    - get: version
      resource: simple-dotnet-version
      params: { bump: patch }
  - task: build
    file: pipeline/ci/build-dotnet.yml
    params:
      ARTIFACT_ID: simple-dotnet
  - put: simple-dotnet-version
    params: { file: version/number }
  - put: cf-test
    params:
      manifest: project/manifest.yml
